display:
  default:
    display_title: Sjálfgefið
    display_options:
      fields:
        title:
          label: Titill
        name:
          label: Höfundur
        changed:
          label: 'Síðast uppfært'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Hlutir per síðu'
            items_per_page_options_all_label: '- Allt -'
      exposed_form:
        options:
          submit_button: Virkja
          reset_button_label: Endursetja
          exposed_sorts_label: 'Raða eftir'
  attachment_1:
    display_title: Viðhengi
  page_1:
    display_title: Síða
