label: Innihald
display:
  default:
    display_title: Sjálfgefið
    display_options:
      title: Innihald
      fields:
        title:
          label: Titill
        type:
          label: Efnisgerð
          separator: ', '
        name:
          label: Höfundur
        status:
          label: Staða
          settings:
            format_custom_false: 'Ekki birt'
            format_custom_true: Birt
        changed:
          label: Uppfært
        langcode:
          label: Tungumál
          separator: ', '
        operations:
          label: Aðgerðir
      pager:
        options:
          tags:
            previous: '< Fyrri'
      exposed_form:
        options:
          submit_button: Sía
          reset_button_label: Endursetja
          exposed_sorts_label: 'Raða eftir'
      filters:
        title:
          expose:
            label: Titill
        type:
          expose:
            label: Efnisgerð
        status:
          expose:
            label: Staða
          group_info:
            group_items:
              1:
                title: Birt
              2:
                title: 'Ekki birt'
        langcode:
          expose:
            label: Tungumál
  page_1:
    display_title: Síða
    display_options:
      menu:
        title: Innihald
      tab_options:
        title: Innihald
