label: Flokkunarhugtak
display:
  default:
    display_title: Sjálfgefið
    display_options:
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Hlutir per síðu'
            items_per_page_options_all_label: '- Allt -'
      exposed_form:
        options:
          submit_button: Virkja
          reset_button_label: Endursetja
          exposed_sorts_label: 'Raða eftir'
      arguments:
        tid:
          exception:
            title: Allt
  feed_1:
    display_title: Veita
  page_1:
    display_title: Síða
