display:
  default:
    display_title: Sjálfgefið
    display_options:
      fields:
        info:
          label: 'Lýsing á blokk'
          separator: ', '
        type:
          separator: ', '
        changed:
          label: Uppfært
        operations:
          label: Aðgerðir
      pager:
        options:
          tags:
            previous: '< Fyrri'
          expose:
            items_per_page_label: 'Hlutir per síðu'
            items_per_page_options_all_label: '- Allt -'
      exposed_form:
        options:
          submit_button: Virkja
          reset_button_label: Endursetja
          exposed_sorts_label: 'Raða eftir'
      filters:
        info:
          expose:
            label: 'Lýsing á blokk'
  page_1:
    display_title: Síða
    display_options:
      menu:
        title: Blokkir
