display:
  default:
    display_title: Sjálfgefið
    display_options:
      title: 'Hverjir eru tengdir'
      exposed_form:
        options:
          submit_button: Virkja
          reset_button_label: Endursetja
          exposed_sorts_label: 'Raða eftir'
  who_s_online_block:
    display_title: 'Hverjir eru tengdir'
    display_options:
      block_description: 'Hverjir eru tengdir'
